services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    environment:
      TZ: 'Europe/Rome'
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
    networks:
      - caddy_wallos

networks:
  caddy_wallos:
    name: caddy_wallos
    external: true
