services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.10.2
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
    networks:
      - frontend 

networks:
  frontend:
    name: frontend
    external: true
