services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    volumes:
      - ./audiobooks:/audiobooks
      - ./books:/books
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=Europe/Rome
    networks:
      - frontend 

networks:
  frontend:
    name: frontend
    external: true
