services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    networks:
      - caddy_komga

networks:
  caddy_komga:
    name: caddy_komga
    external: true
