services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    restart: 'unless-stopped'
    networks:
      - frontend 

networks:
  frontend:
    name: frontend
    external: true
