services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${DEFAULT_PASSWORD}
    volumes:
      - "./data:/app/data"
    networks:
      - frontend 
    restart: 'unless-stopped'

networks:
  frontend:
    name: frontend
    external: true
