services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${DEFAULT_PASSWORD}
    volumes:
      - "./data:/app/data"
    networks:
      - caddy_gotify
    restart: 'unless-stopped'

networks:
  caddy_gotify:
    name: caddy_gotify
    external: true
