version: "3"
services:
  nextcloud-db:
    image: mariadb:11.2
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  nextcloud:
    image: nextcloud:28.0
    container_name: nextcloud
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=${PROXY_IP}
    restart: 'unless-stopped'
    links:
      - nextcloud-db
    networks:
      - frontend 
      - backend

  code:
    image: collabora/code:24.04.2.1.1
    container_name: nextcloud-code
    environment:
      - username=admin
      - password=${COLLABORA_PASSWORD}
      - domain=${NEXTCLOUD_FQDN}
      - dictionaries=en it
      - extra_params=--o:ssl.enable=true --o:ssl.termination=false
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    cap_add:
      - MKNOD
    tty: true
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true
  backend:

volumes:
  database:

