version: "3.5"

services:
  diun:
    image: crazymax/diun:4.26
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=${TIMEZONE}
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}"
      - "DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}"
    restart: always
