services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./data:/datastore
    restart: unless-stopped
    networks:
      - caddy_changedetection
    env_file:
      - .env

networks:
  caddy_changedetection:
    name: caddy_changedetection
    external: true
