services:
  actual_server:
    image: actualbudget/actual-server
    container_name: actual_server
    volumes:
      - ./data:/data
    restart: 'unless-stopped'
    networks:
      - frontend 

networks:
  frontend:
    name: frontend
    external: true
