version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.13
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: 'unless-stopped'
    networks:
      - frontend 

networks:
  frontend:
    name: frontend
    external: true
