version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.13
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: 'unless-stopped'
    networks:
      - frontend 

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr-config:/config
      - ./media/movies:/movies
    restart: 'unless-stopped'
    networks:
      - frontend 

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr-config:/config
      - ./media/tvshows:/tv
    restart: 'unless-stopped'
    networks:
      - frontend 


networks:
  frontend:
    name: frontend
    external: true
