<?php
/**
 * AgenDAV instance configuration.
 *
 * Rendered to settings.php by init.sh — edit this template and re-run it.
 * settings.php is gitignored because it carries both per-installation secrets.
 *
 * Only values that differ from the defaults are listed here; the full
 * annotated set lives in config/default.settings.php inside the image.
 */

return [
    'site.title' => '${AGENDAV_SITE_TITLE}',

    // SQLite is enough for a single user. pdo_sqlite is compiled into the
    // php:8.5 base image, so upstream's Dockerfile needs no extra extension.
    // The file lives on the ./data bind mount, and pre-backup.sh stops the
    // container so it can be snapshotted consistently.
    'db.options' => [
        'driver' => 'pdo_sqlite',
        'path' => '/app/database/agendav.sqlite',
    ],

    // PHP file sessions. AgenDAV defaults to 'pdo', which keeps sessions in
    // the database via Symfony's PdoSessionHandler — and app/services.php
    // wires that handler with LOCK_ADVISORY, so against SQLite every single
    // request dies at session_start() with:
    //
    //     DomainException: SQLite does not support advisory locks
    //
    // The lock mode is hardcoded upstream (chosen so the session connection
    // cannot collide with Doctrine's own transactions) and cannot be
    // overridden from here, so file sessions are the only option while the
    // database is SQLite.
    //
    // Consequence: sessions live inside the container and do not survive it
    // being recreated, so `init.sh` logs you out. Logging back in needs the
    // app token again.
    'session.handler' => 'native',

    // Internal address of the CalDAV server. This is OpenCloud's proxy, not
    // Radicale directly: the proxy validates the Basic credentials below,
    // resolves the user and forwards to radicale:5232 with X-Remote-User set.
    // Reached over the shared `frontend` docker network.
    //
    // Deliberately no '%u' placeholder. AgenDAV substitutes one if present,
    // but it must not be used here: Radicale keys collections by OpenCloud's
    // opaque user ID (a UUID), not the username, so a hand-built path gets a
    // 403. AgenDAV instead PROPFINDs DAV:current-user-principal at this URL
    // and follows calendar-home-set from the response, which is the only
    // supported way to find the path. See opencloud/README.md.
    'caldav.baseurl' => 'http://opencloud:9200/caldav/',

    // Basic, not digest: the login password is an OpenCloud app token
    // (PROXY_ENABLE_APP_AUTH), and the proxy expects credentials it can read
    // directly. CalDAV clients cannot do an OIDC browser flow.
    'caldav.authmethod' => 'basic',

    // Per-calendar URLs shown in the UI. app.js concatenates this value with
    // the collection's absolute path, so it must be a bare origin with no
    // trailing slash: '<origin>' + '/caldav/<uuid>/def-calendar/'.
    'caldav.publicurls' => true,
    'caldav.baseurl.public' => '${OPENCLOUD_FQDN}',

    // Per-installation secrets, generated by the operator. See .env.sample.
    'csrf.secret' => '${AGENDAV_CSRF_SECRET}',
    // Encrypts the app token held in each session. Changing it invalidates
    // existing sessions, which only means logging in again.
    'session.encryption.key' => '${AGENDAV_SESSION_KEY}',

    // Log to the container's stdout so `docker logs` and Dozzle see it,
    // rather than accumulating dated files under ./var/log.
    'log.file' => 'php://stdout',

    // Off by default upstream, and left off: enabling it makes the server
    // fetch arbitrary user-supplied URLs, which on a host whose docker
    // networks carry unauthenticated internal services is an SSRF risk.
    'calendar.subscriptions' => false,

    // Deprecated upstream and DAViCal-only. Explicitly off so it cannot be
    // mistaken for working sharing against Radicale.
    'calendar.sharing' => false,

    'defaults.timezone' => '${AGENDAV_TIMEZONE}',
    'defaults.language' => 'en',
    'defaults.time_format' => '24',
    'defaults.date_format' => 'dmy',
    'defaults.weekstart' => 1,
];
